# Generated by Django 4.2.2 on 2023-06-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_user_birth_date'),
        ('cards', '0002_rename_header_card_headline_alter_user_bio_and_more'),
    ]

    operations = [
    ]
