# Generated by Django 4.2.2 on 2023-06-22 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_merge_20230622_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='text',
        ),
        migrations.AddField(
            model_name='card',
            name='back_text_font',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='background_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='border_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='font_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='front_text_font',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='header_font',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_card', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
