# Generated by Django 4.2.2 on 2023-06-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_follow_user_following_this_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_following_this_user',
        ),
    ]
