# Generated by Django 4.2.2 on 2023-06-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_follow_user_following_this_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user_following_this_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows_this_user', to='cards.follow'),
        ),
    ]
