# Generated by Django 4.2.2 on 2023-06-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_follow_user_following_this_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='back_text',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_following_this_user',
        ),
        migrations.AddField(
            model_name='card',
            name='inner_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='front_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='this_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user_this_user_is_following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
