# Generated by Django 4.2.2 on 2023-06-23 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_back_text_alter_card_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='card',
            name='sent_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='back_text_font',
            field=models.TextField(blank=True, choices=[('Script', 'Script'), ('Serif', 'Serif'), ('Sans Serif', 'Sans Serif')], null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_text_font',
            field=models.TextField(blank=True, choices=[('Script', 'Script'), ('Serif', 'Serif'), ('Sans Serif', 'Sans Serif')], null=True),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_as_follower', to=settings.AUTH_USER_MODEL)),
                ('user_follows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
