# Generated by Django 4.2.2 on 2023-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_back_text_alter_card_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='front_text_font',
            field=models.TextField(blank=True, choices=[('Script', 'Script'), ('Serif', 'Serif'), ('Sans Serif', 'Sans Serif')], null=True),
        ),
    ]
