# Generated by Django 4.2.2 on 2023-06-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_back_text_alter_card_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sender',
        ),
        migrations.AddField(
            model_name='card',
            name='received_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='sent_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
