# Generated by Django 4.2.2 on 2023-06-23 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_receiver_remove_card_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='sent_cards',
            new_name='sent_by_user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='received_cards',
        ),
        migrations.AddField(
            model_name='card',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
