# Generated by Django 4.2.2 on 2023-06-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_receiver_remove_card_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Purple', 'Purple'), ('Orange', 'Orange')], null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='border_color',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Purple', 'Purple'), ('Orange', 'Orange')], null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Purple', 'Purple'), ('Orange', 'Orange')], null=True),
        ),
    ]
