# Generated by Django 4.2.2 on 2023-06-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_front_text_font'),
        ('cards', '0008_rename_sent_cards_card_sent_by_user_and_more'),
    ]

    operations = [
    ]
