# Generated by Django 4.2.2 on 2023-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_background_color_alter_card_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='border_decor',
            field=models.CharField(blank=True, choices=[('Dotted', 'Dotted'), ('Solid', 'Solid'), ('No Border', 'No Border')], null=True),
        ),
    ]
