# Generated by Django 4.2.2 on 2023-06-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_remove_card_border_decor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='border_decor',
            field=models.CharField(blank=True, choices=[('Dotted', 'Dotted'), ('Solid', 'Solid'), ('No Border', 'No Border')], null=True),
        ),
    ]
