# Generated by Django 4.2.2 on 2023-06-24 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_rename_user_follow_logged_in_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='logged_in_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_who_user_follows',
        ),
        migrations.AddField(
            model_name='follow',
            name='user_as_follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follows_by_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='user_being_followed',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='follows_to_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
