# Generated by Django 4.2.2 on 2023-06-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_rename_user_as_follower_follow_user_is_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users_user_following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
