# Generated by Django 4.2.2 on 2023-06-25 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_user_follows_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='user_follows',
            field=models.ManyToManyField(related_name='users_user_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
