# Generated by Django 4.2.2 on 2023-06-25 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_remove_user_follows_user_user_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows_user', models.ManyToManyField(related_name='followers_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
