# Generated by Django 4.2.2 on 2023-06-25 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follower_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
