# Generated by Django 4.2.2 on 2023-06-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_follower_follower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower_user',
        ),
        migrations.AddField(
            model_name='user',
            name='follower_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='cards.follower'),
            preserve_default=False,
        ),
    ]
