# Generated by Django 4.2.2 on 2023-06-25 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_remove_follower_follower_user_user_follower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follows_user',
        ),
        migrations.AddField(
            model_name='follower',
            name='user_who_follows_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follows_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower_user',
        ),
        migrations.AddField(
            model_name='user',
            name='follower_user',
            field=models.ManyToManyField(related_name='users_following_user', to='cards.follower'),
        ),
    ]
