# Generated by Django 4.2.2 on 2023-06-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_remove_follower_follows_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follower_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_bool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_allowed_to_follow_user', to='cards.follower'),
            preserve_default=False,
        ),
    ]
