# Generated by Django 4.2.2 on 2023-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_follower_follower_bool_user_follower_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_bool',
        ),
        migrations.AddField(
            model_name='user',
            name='follower_bool',
            field=models.ManyToManyField(related_name='users_allowed_to_follow_user', to='cards.follower'),
        ),
    ]
