# Generated by Django 4.2.2 on 2023-06-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_remove_follower_user_who_follows_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follower_user',
            field=models.ManyToManyField(related_name='users_following_user', to='cards.follower'),
        ),
    ]
