# Generated by Django 4.2.2 on 2023-06-25 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_follower_follower_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_user',
            field=models.ManyToManyField(related_name='users_following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
