# Generated by Django 4.2.2 on 2023-06-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_alter_follower_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='user_being_followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers_by_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
