# Generated by Django 4.2.2 on 2023-06-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_follower_user_being_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_bool',
        ),
    ]
