# Generated by Django 4.2.2 on 2023-06-25 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0031_remove_user_follower_bool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower_bool',
            new_name='follows_user',
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower_user',
            field=models.ManyToManyField(related_name='followers_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
