# Generated by Django 4.2.2 on 2023-06-25 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0032_rename_follower_bool_follower_follows_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows_user',
            field=models.ManyToManyField(related_name='users_following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
