# Generated by Django 4.2.2 on 2023-06-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0034_userfollowing_remove_user_follows_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='this_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='user_this_user_is_following',
        ),
    ]
