# Generated by Django 4.2.2 on 2023-06-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0035_rename_user_id_userfollowing_this_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_user', to=settings.AUTH_USER_MODEL)),
                ('user_this_user_is_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_these_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
