# Generated by Django 4.2.2 on 2023-06-26 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0036_follow_delete_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user_following_this_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follows_this_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
