# Generated by Django 4.2.2 on 2023-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0037_follow_user_following_this_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_following_this_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_this_user', to='cards.follow'),
        ),
    ]
